# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'frhlpipes-conn'
    subscriptionId: '4ccb9431-8866-450b-869f-32a53c250f7f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'frhlpipes'
    location: 'West US 2'
    templateLocation: 'URL of the file'
    # csmFileLink: 'https://raw.githubusercontent.com/FreeheelGreg/frhlpipes-repo/main/create_web_app/azuredeploy.json?token=GHSAT0AAAAAACCKTUBD5M7YVPGBIKENZ2HKZCXX6PA'
    csmFileLink: 'https://raw.githubusercontent.com/FreeheelGreg/frhlpipes-repo/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName frhlpipes'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    displayName: 'Run a multi-line script'
